### ISSUE TITLE
Player ID [Feature Request]

### ISSUE THREAD

**Issue by drachnien** [PeteAUK/bitsand#9]
Can the player ID be added to the OOC information section please.

**Comment by PeteAUK** [comment]
No problems, will implement this shortly

**Comment by StuLeanJackalsNPC** [comment]
Hi guys,

Has this been implemented yet? If so, how do we update current system to incorporate it, or should it be automatic?

Cheers

Stu

**Comment by PeteAUK** [comment]
Apologies on this, I thought I'd rolled out the update to cater for player id's.

I have now added a new "Player Number" field into the OOC Details page, although this is an optional field if you've not completed it each player will get a green box prompting them to do so on each page.  Where I've spotted it, I've also modified the old "Player ID" field to simply say "ID" in an effort to minimise confusion (I felt it was better to keep ID as the internal identifier and Number as the item on your player card).

The back end will now display the player number in addition to the other fields, including on the CSV export.  The backend and CSV pull this data "on the fly" so if a player adds their number after the booking, the backend will reflect this (in the same way as changing a surname and medical information).

The additional field in the database (`plPlayerNumber - VARCHAR(24) NOT NULL`) should be added automatically when you first view the admin home page.

To update, if you're running Bitsand v8.1 or greater and head over to the admin area, you should get instructions and an option to automatically perform the upgrade.  If you're running an older version or it's not working, raise a new issue here or poke me using Facebook or similar

**Comment by StuLeanJackalsNPC** [comment]
Hi Pete,

Think we are running an older version, didn't receive an upgrade notification.

**Comment by PeteAUK** [comment]
No problems (it's one of the reasons I added in the new upgrade functionality in v8 when I took over).  To upgrade from an older version, you'll need to download the the source code and overwrite the code on the server.  If you're not comfortable to handle this, I'm happy to do the upgrade if you're able to pass me FTP access - if so let me know and I'll get an e-mail address sent over to you

**Comment by StuLeanJackalsNPC** [comment]
Cool, I'll get back to you as I don't think my login gives me that level of
access either! ;)

**Comment by jfharden** [comment]
Just updated to the very latest commit, great work :) Thanks

**Comment by drachnien** [comment]
Hi Pete, 
Would it be possible for you to help with the upgrade to the lions version. I've inherited it and it seems to be quite outdated and I'm lost :(

**Comment by PeteAUK** [comment]
More than happy to - apologies on the delay on replying.  If you let me know the best way of getting hold of you, we can work out logins and stuff.

**Comment by drachnien** [comment]
Thank you very much, Easiest to get me on [e-mail sent and removed to prevent spam]
